[package]
name = "baddown"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
parser = { path = "parser" }
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }

[workspace]
members = [
    "parser",
]

